name: Continous Integration Github Action

on:
  push:
  pull_request:
jobs:
  run-static-codebase-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install depedencies
        run: npm i
      - name: Run formatter
        run: npm run format
      - name: Run type-check
        run: npm run type-check

    run-test-suite:
      runs-on:
      steps:
      - uses: actions/checkout@v4
      - name: Install depedencies
        run: npm i

